/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.LoginData;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muri
 */
public final class Login extends javax.swing.JDialog {

  private boolean pressedConnect;
  private LoginData data;
  
  
  public Login(java.awt.Frame parent, boolean modal) throws Exception {
    super(parent, modal);
    initComponents();
    setSize(new Dimension(300, 200));
    setMinimumSize(new Dimension(200, 200));
    setMaximumSize(new Dimension(500, 300));
    setLocationRelativeTo(parent);
 
  }

  public boolean isPressedConnect() {
    return pressedConnect;
  }
  
  public void setPressedConnect (boolean pressed) {
    pressedConnect = pressed;
  }
  
  public void setLogin (LoginData data) throws Exception {
      jTextIP.setText(data.getRaspIP());
      jTextPassword.setText(data.getPassword());
      jTextPort.setText(Integer.toString(data.getPort()));
  }
  
  public LoginData getLoginData () {
    return data;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel3 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabelIP = new javax.swing.JLabel();
    jLabelPassword = new javax.swing.JLabel();
    jTextPort = new javax.swing.JTextField();
    jLabelPort = new javax.swing.JLabel();
    jTextIP = new javax.swing.JTextField();
    jTextPassword = new javax.swing.JPasswordField();
    jPanel2 = new javax.swing.JPanel();
    jButCancel = new javax.swing.JButton();
    jButConnect = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel3.setLayout(new java.awt.GridBagLayout());

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
    jLabel4.setText("MTR-login");
    jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

    getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabelIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelIP.setText("IP-Adresse:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jLabelIP, gridBagConstraints);

    jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelPassword.setText("Passwort:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jLabelPassword, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.ipady = 1;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jTextPort, gridBagConstraints);

    jLabelPort.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelPort.setText("Port:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jLabelPort, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.ipady = 1;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jTextIP, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.ipady = 1;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    jPanel1.add(jTextPassword, gridBagConstraints);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jButCancel.setText("Abbrechen");
    jButCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButCancelActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    jPanel2.add(jButCancel, gridBagConstraints);

    jButConnect.setText("Verbinden");
    jButConnect.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButConnectActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
    jPanel2.add(jButConnect, gridBagConstraints);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelActionPerformed
    pressedConnect = false;
    dispose();
  }//GEN-LAST:event_jButCancelActionPerformed

  private void jButConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConnectActionPerformed
    String ip = jTextIP.getText();
    String password = jTextPassword.getText();
    String port = jTextPort.getText();
    
    try {
      data = new LoginData(ip, password, port);
      pressedConnect = true;
      dispose();
    } catch (Exception ex) {
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Fehlerhafte Eingabe", JOptionPane.ERROR_MESSAGE); 
    }
    
  }//GEN-LAST:event_jButConnectActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          Login dialog = new Login(new javax.swing.JFrame(), true);
          dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
              System.exit(0);
            }
          });
          dialog.setVisible(true);
        } catch (Exception ex) {
          Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButCancel;
  private javax.swing.JButton jButConnect;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabelIP;
  private javax.swing.JLabel jLabelPassword;
  private javax.swing.JLabel jLabelPort;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField jTextIP;
  private javax.swing.JPasswordField jTextPassword;
  private javax.swing.JTextField jTextPort;
  // End of variables declaration//GEN-END:variables
}
